title: CaPTion Workshop @ MICCAI 2022
description: MICCAI 2022 Workshop on "Cancer Prevention through early detecTion"
show_downloads: true
header: assets/images/CaPTion_logo.png
google_analytics:
theme: jekyll-theme-cayman
